### ISSUE TITLE
[DataCap Application] <Cloud_Period> - <Cloud_Plan>

### ISSUE THREAD

**Issue by yueyueyuelonglong** [Lind111/EF#24]
### Data Owner Name

Greis

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.htymeta.com/

### Social Media Handle

longyue19960810@gmail.com

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1qfm5gkrguixoy6ycf2o4obij5tkyi6pzgs2dtxy

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As a Hantang cloud new retail intelligent solution, Cloud Watch has strong technical strength and rich industry experience, focusing on the traditional offline merchant digitalization, unmanned upgrade and transformation of intelligent new retail platform. Through the intelligent voice intercom system, provide a combination of artificial + intelligent 7*24*365 cloud duty service. Without changing the original business model, let the retail stores complete the digital and intelligent upgrading and transformation, and achieve on-site duty during the peak period and cloud duty during the low peak period.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Heterogeneous GPU computing container cluster management services, cloud resource pool management services, node pool management services, providing web-based user-self-service portal.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://www.htymeta.com/news_detail-1754.html
http://www.htymeta.com/news_detail-1759.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03178191 US
f03178188 US
f03178173 US
f03178165 US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Lind111** [comment]
Sorry for taking so long to reply, there are no datacaps left so I can't go ahead with the approval at the moment

**Comment by Lind111** [comment]
First, please click on https://github.com/filecoin-project/notary-governance/issues/1056#issuecomment-1890621214 to view my allocation rules

**Comment by Lind111** [comment]
Could you send an email with business license to [qq248245620@gmail.com](mailto:qq248245620@gmail.com) in order to confirm your identity?The email should include the miner ID, the business entity, a list of sps locations you will be working with

**Comment by Lind111** [comment]
Too long without updates will be closed
