### ISSUE TITLE
[DataCap Application] <Beijing Zhongnong Leaf Eating Grass Natural Science Research Institute> - <Virus nucleic acid sequence dataset>

### ISSUE THREAD

**Issue by luhong123** [Lind111/EF#4]
### Version

1

### DataCap Applicant

Beijing Zhongnong Leaf Eating Grass Natural Science Research Institute

### Project ID

1

### Data Owner Name

Beijing Zhongnong Leaf Eating Grass Natural Science Research Institute

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

no

### Social Media Handle

QQ 3415634156

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

8

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

2

### Unit for expected size of single dataset

PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1

### Unit for weekly allocation of DataCap requested

PiB

### On-chain address for first allocation

f1266w3mjcy6vvzv22nclpk5xcttk6p43hkavywlq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
北京中农食用叶草自然科学研究院（前身为北京中科全脑自然科学研究所）成立于2018年，位于北京。它是一家主要从事研究和实验开发的企业。企业注册资本为人民币100万元。
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
病毒核酸序列数据集、病毒核酸数据集、蛋白质序列数据库、细菌数据集、古菌数据集等
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
已经申请过大数据，有相关经验，可以参考
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2090
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2090

之前的大数据没额度了，无法再次存储
```

### Please share a sample of the data

```text
RNA DNA
https://www.alipan.com/s/sQwUTZyzeEs
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
其他社交渠道如微信，QQ，TG
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02816666 Huhehaote
f01128206 Hong Kong
f02215209 Californial
f02237006 Singapore
f02519100 Guangzhou
f03034045     Tokyo
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Lind111** [comment]
It's not during working hours now, I will take time to check the information later, thank you for your understanding!

**Comment by Lind111** [comment]
浏览了你之前申请的LDN的历史信息，看起来不错，机器人报告一切正常

**Comment by Lind111** [comment]
请发送你们公司的营业执照至qq248245620@gmail.com以再次确认您的身份，谢谢

**Comment by Lind111** [comment]
想问一下你这次的数据集跟上次的一样吗？还是有区别

**Comment by Lind111** [comment]
已确认

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
由于第一轮发放了超过规定的datacap，这轮将会取回数据验证

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
Closed after removing datacap, feel free to apply again!
